### ISSUE TITLE
[URGENT] Removal request

### ISSUE THREAD

**Issue by hungrywerewolf** [AizOfMulia/IDP00104#2]
https://github.com/AizOfMulia/IDP00104/blob/0ec91e589edf3e7686f853c2978783e2e8cd8c88/src/CalculateShapes.java#L489

https://github.com/AizOfMulia/IDP00104/blob/0ec91e589edf3e7686f853c2978783e2e8cd8c88/src/CalculateShapes.java#L485

**Comment by AizOfMulia** [comment]
Noted.
